name: Auto approve PRs by dependabot

# Trigger the workflow on pull request
on: pull_request_target

jobs:
  autoapprove:
    name: Auto-Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.CI_TOKEN }}